palette:
  top: '#cd2d2d'
  bottom: '#d64e4e'
  bg: '#ffffff'
  sidebar: '#f1f4f0'
  sidebarborders: '#ededed'
  footer: '#1f1d1c'
  titleslogan: '#fffeff'
  text: '#888888'
  link: '#d6121f'
logo: 'public://color/bartik-bd191568/logo.svg'
stylesheets:
  - 'public://color/bartik-bd191568/colors.css'
files:
  - 'public://color/bartik-bd191568/logo.svg'
  - 'public://color/bartik-bd191568/colors.css'
