_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
langcode: es
site_name: Bloodline
short_name: Bloodline
description: ''
start_url: /
lang: es
theme_color: '#000000'
background_color: '#000000'
display: fullscreen
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
offline_page: /offline
cache_version: '1'
cross_origin: false
skip_waiting: false
image: '/sites/default/files/pwa/Webp.net-resizeimage (2).png'
image_small: '/sites/default/files/pwa/Webp.net-resizeimage (2).pngcopy.png'
image_very_small: '/sites/default/files/pwa/Webp.net-resizeimage (2).pngcopy2.png'
