_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
langcode: es
first_day: 0
country:
  default: NI
timezone:
  default: America/Managua
  user:
    configurable: false
    default: 0
    warn: false
